# Meta Data for SEO

## Homepage
title = "XiuXin"
titleSeparator = "-"
titleAddition = "文档"
description = "v2rayA 是一个支持全局透明代理的 V2Ray Linux 客户端，同时兼容SS、SSR、Trojan(trojan-go)、PingTunnel协议。"

## Open Graph
images = ["v2raya.png"]
ogLocale = "zh_cn"
ogImageHeight = "320"
ogImageWidth = "640"
domainTLD = "ikxiuxin.com"
titleHome = "v2rayA Doc"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
schemaType = "Organization"
schemaName = "v2rayA"
schemaAuthor = "v2rayA"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/juneover24/XiuXinWeb"
schemaLocale = "zh-CN"
schemaLogo = "android-chrome-512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "v2raya.png"
schemaImageWidth = 289
schemaImageHeight = 117
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://ikxiuxin.com"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "CC-BY-SA | Copyright (c) 2021 - {year} XiuXin Organization"
copyright = "Copyright (c) 2021 - {year} XiuXin Organization"

# Alert
alert = false
alertText = "Like v2rayA? <a class=\"alert-link\" href=\"https://github.com/v2rayA/v2rayA/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/juneover24/XiuXinWeb"
editPage = true

# Contributors
githubContributors = true
githubUser = "XiuXinWeb"
githubRepo = "XiuXinWeb"
githubDocRepo = "juneover24.github.io"
githubDocTree = "main"
githubContributorsAPI = ""

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  collapsibleSidebar = true
  docsNavigation = true
  lastModified = true

[dateFormat]
lastUpdated = "2006年01月02日 15:04:05 MST"
